# step 1: build stage
FROM node:18.16.0-alpine AS build-stage

WORKDIR /app

COPY . .
RUN npm install
RUN npm run build

# step 2: production stage
FROM nginx:1.12-alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]